version: '2'
services:
    p1-app:
        image: p1
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://p1-mariadb:3306/p1
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    p1-mariadb:
        extends:
            file: mariadb.yml
            service: p1-mariadb
