version: '3'
services:
    p1-mariadb:
        image: mariadb:10.3.7
        volumes:
            - ~/volumes/jhipster/P1/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_PASSWORD=uN1v3rsItY_0f_vVi3n
            - MYSQL_DATABASE=p1
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
